devguide: 
  gretting: acccount

---

spring: 
  profiles: local 

devguide: 
  gretting: "변경된 로컬환경입니다."

---

spring: 
  profiles: dev
devguide: 
  gretting: "개발 환경입니다."

---

spring: 
  profiles: stage
devguide: 
  gretting: "스테이징 환경입니다."

---

spring: 
  profiles: product
devguide: 
  gretting: "상용 환경입니다."
